var BILI_API='https://api.bilibili.com',BILI_UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36';
var BILI_WBI=[46,47,18,2,53,8,23,32,15,50,10,31,58,3,45,35,27,43,5,49,33,9,42,19,29,28,14,39,12,38,41,13,37,48,7,16,24,55,40,61,26,17,0,1,60,51,30,4,22,25,54,21,56,59,6,63,57,62,11,36,20,34,44,52];
function clean(text){return String(text||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();}
function secure(value){value=String(value||'');return value.indexOf('//')===0?'https:'+value:value;}
function* biliRequest(route,params,state,signed){params=Object.assign({},params||{});if(signed){if(!state.wbi||Date.now()-(state.wbiAt||0)>21600000){var nav=yield* biliRequest('/x/web-interface/nav',{},state,false),images=nav.wbi_img||{},combined=[images.img_url,images.sub_url].map(function(address){return String(address||'').split('/').pop().split('.')[0];}).join('');if(combined.length<64)throw new Error('WBI 签名密钥缺失');state.wbi=BILI_WBI.map(function(index){return combined[index];}).join('').slice(0,32);state.wbiAt=Date.now();}Object.keys(params).forEach(function(key){params[key]=String(params[key]).replace(/[!'()*]/g,'');});params.wts=String(Math.floor(Date.now()/1000));params.w_rid=md5(query(params)+state.wbi);}var result=yield* json(BILI_API+route+'?'+query(params),{credential:true,headers:{'User-Agent':BILI_UA,'Referer':'https://www.bilibili.com/','Origin':'https://www.bilibili.com','Accept':'application/json, text/plain, */*'}});if(result.code&&!(route==='/x/web-interface/nav'&&Number(result.code)===-101&&result.data))throw new Error('哔哩哔哩接口拒绝请求 '+result.code);if(!result.data)throw new Error('接口缺少有效数据');return result.data;}
function biliDrama(row){var owner=row.owner||{},stats=row.stat||{},id=String(row.bvid||'');return {id:'bilibili:'+id,source:'bilibili',sourceId:id,title:clean(row.title).slice(0,256),description:clean(row.desc||row.description).slice(0,12000),cover:secure(row.pic),episodes:Number(row.videos)||1,category:clean(row.typename||row.tname)||'视频',views:String(first(row,['play','view'],stats.view||'')),creatorId:String(owner.mid||row.mid||''),creatorName:clean(owner.name||row.author),creatorAvatar:secure(owner.face||row.upic)};}
function biliRows(rows){return array(rows).filter(function(row){return /^BV[0-9A-Za-z]{10}$/.test(String(row.bvid))&&row.title&&(!row.goto||row.goto==='av');}).map(biliDrama);}
function xml(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function representation(row){var address=secure(row.baseUrl||row.base_url),segment=row.SegmentBase||row.segment_base||{},init=segment.Initialization||segment.initialization,index=segment.indexRange||segment.index_range;if(!/^https:\/\//.test(address)||!/^\d+-\d+$/.test(String(init))||!/^\d+-\d+$/.test(String(index)))return null;return {url:address,init:init,index:index,codec:String(row.codecs||''),height:Number(row.height)||0,width:Number(row.width)||0,bandwidth:Number(row.bandwidth)||1};}
function adaptation(row,kind){return '<AdaptationSet contentType="'+kind+'" mimeType="'+kind+'/mp4" segmentAlignment="true"><Representation id="'+kind+'" bandwidth="'+row.bandwidth+'" codecs="'+xml(row.codec)+'"'+(kind==='video'?' width="'+row.width+'" height="'+row.height+'"':'')+'><BaseURL>'+xml(row.url)+'</BaseURL><SegmentBase indexRange="'+row.index+'"><Initialization range="'+row.init+'"/></SegmentBase></Representation></AdaptationSet>';}
function* sourceExecute(action,input,state){var drama=input.drama||{},id=drama.sourceId||String(drama.id||'').split(':').pop(),page=Number(input.page)||1;
 if(action==='categories')return {items:[{id:'for-you',name:'个性推荐'},{id:'following',name:'正在关注'},{id:'ranking',name:'排行'}]};
 if(action==='account'){var data=yield* biliRequest('/x/web-interface/nav',{},state,false);return {loggedIn:data.isLogin===true,name:String(data.uname||''),mid:String(data.mid||''),avatar:secure(data.face)};}
 if(action==='catalog'||action==='search'||action==='check'){
  var category=input.category||'for-you',data,items=[],more=false;
  if(input.query){data=yield* biliRequest('/x/web-interface/wbi/search/type',{search_type:'video',keyword:input.query,page:page,page_size:20,platform:'pc',web_location:'1430654',order:'totalrank'},state,true);items=biliRows(data.result);more=data.numPages?page<Number(data.numPages):array(data.result).length>=20;}
  else if(category==='ranking'){data=yield* biliRequest('/x/web-interface/ranking/v2',{rid:'0',type:'all'},state,false);items=biliRows(array(data.list).slice((page-1)*20,page*20));more=page*20<array(data.list).length;}
  else if(category==='following'){var offset=page===1?'':state.followOffset||'';for(var attempt=0;attempt<3;attempt++){data=yield* biliRequest('/x/polymer/web-dynamic/v1/feed/all',{type:'video',offset:offset,timezone_offset:'-480',features:'itemOpusStyle'},state,false);if(!Array.isArray(data.items))throw new Error('关注数据结构无效');data.items.forEach(function(row){if(row.type!=='DYNAMIC_TYPE_AV')return;var modules=row.modules||{},archive=(((modules.module_dynamic||{}).major||{}).archive)||{},author=modules.module_author||{};items=items.concat(biliRows([{bvid:archive.bvid,title:archive.title,pic:archive.cover,desc:archive.desc,owner:{mid:author.mid,name:author.name,face:author.face}}]));});var next=String(data.offset||'');more=(data.has_more===true||Number(data.has_more)===1)&&next!==offset&&next!=='';offset=next;if(items.length||!more)break;}state.followOffset=offset;}
  else{data=yield* biliRequest('/x/web-interface/wbi/index/top/feed/rcmd',{version:'1',feed_version:'V8',homepage_ver:'1',ps:'20',fresh_idx:String(page),brush:String(page),fresh_type:'4'},state,true);if(!Array.isArray(data.item))throw new Error('推荐数据结构无效');items=biliRows(data.item);more=data.item.length>0;}
  return {items:items,count:items.length,hasMore:more,fresh:true};
 }
 if(action==='detail'||action==='metadata'){var data=yield* biliRequest('/x/web-interface/wbi/view',{bvid:id},state,true);if(String(data.bvid)!==id)throw new Error('视频标识不匹配');state.aids=state.aids||{};state.aids[id]=String(data.aid);var chapters=array(data.pages);if(!chapters.length)chapters=[data];chapters=chapters.slice(0,5000).filter(function(row){return Number(row.cid)>0;}).map(function(row,index){var number=Number(row.page)||index+1;return {id:'bilibili:'+id+':'+row.cid,cid:String(row.cid),title:clean(row.part)||'P'+number,currentEpisode:number};});if(!chapters.length)throw new Error('未返回可用分 P');return {drama:biliDrama(data),chapters:chapters};}
 if(action==='resolve'){
  var cid=input.chapter.cid||String(input.chapter.id||'').split(':').pop(),height=Number(input.quality)||0,qn=height>=4320?127:height>=2160?120:height>=1080?80:height>=720?64:height>=480?32:height>=360?16:height?6:80;
  var data=yield* biliRequest('/x/player/wbi/playurl',{bvid:id,cid:cid,qn:qn,fnval:'4048',fnver:'0',fourk:'1'},state,true);if(Number(data.drm_tech_type)>0)throw new Error('受保护的视频不能使用此播放器');var dash=data.dash||{},video=array(dash.video).map(representation).filter(Boolean).sort(function(a,b){return b.height-a.height||(/avc|h264/i.test(b.codec)?1:0)-(/avc|h264/i.test(a.codec)?1:0)||b.bandwidth-a.bandwidth;}),audio=array(dash.audio).map(representation).filter(Boolean).sort(function(a,b){return (/mp4a/i.test(b.codec)?1:0)-(/mp4a/i.test(a.codec)?1:0)||b.bandwidth-a.bandwidth;})[0];if(!video.length)throw new Error('没有可播放的 DASH 视频轨道');if(array(dash.audio).length&&!audio)throw new Error('音频轨道无效，已避免返回无声视频');var selected=height?video.find(function(row){return row.height<=height;})||video[video.length-1]:video[0];var manifest='<?xml version="1.0" encoding="UTF-8"?><MPD xmlns="urn:mpeg:dash:schema:mpd:2011" type="static" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT1.5S" mediaPresentationDuration="PT'+(Number(data.timelength)/1000).toFixed(3)+'S"><Period>'+adaptation(selected,'video')+(audio?adaptation(audio,'audio'):'')+'</Period></MPD>';return {url:selected.url,manifest:manifest,manifestType:'dash',quality:selected.height,qualities:video.map(function(row){return row.height;}),headers:{'Referer':'https://www.bilibili.com/video/'+id+'/','User-Agent':BILI_UA}};
 }
 if(action==='comments'){var current=Number(input.cursor)||1;if(current>10)return empty();var aid=state.aids&&state.aids[id];if(!aid){var view=yield* biliRequest('/x/web-interface/wbi/view',{bvid:id},state,true);aid=String(view.aid);}var data=yield* biliRequest('/x/v2/reply',{oid:aid,type:'1',pn:current,ps:'20',sort:'2'},state,false),rows=array(data.replies),total=Number((data.page||{}).count)||0;return {items:rows.slice(0,20).map(function(row){var user=row.member||{},content=row.content||{};return {id:String(row.rpid),author:clean(user.uname),avatar:secure(user.avatar),text:String(content.message||'').slice(0,4000),likes:Number(row.like)||0};}),cursor:String(current+1),total:total,hasMore:current<10&&rows.length>0&&current*20<total};}
 if(action==='creator'){var mid=drama.creatorId,cursor=Number(input.cursor)||1;if(!mid){var view=yield* biliRequest('/x/web-interface/wbi/view',{bvid:id},state,true);mid=String((view.owner||{}).mid||'');}if(!/^\d+$/.test(mid))throw new Error('没有作者 UID');var data=yield* biliRequest('/x/space/wbi/arc/search',{mid:mid,pn:cursor,ps:'30',tid:'0',order:'pubdate',platform:'web',web_location:'1550101'},state,true),info={};if(cursor===1){try{info=yield* biliRequest('/x/web-interface/card',{mid:mid},state,false);}catch(error){}}var card=info.card||{},items=biliRows((data.list||{}).vlist);return {items:items,name:clean(card.name)||drama.creatorName,avatar:secure(card.face)||drama.creatorAvatar,userId:mid,bio:clean(card.sign),followers:card.fans,following:card.attention,likes:info.like_num,cursor:String(cursor+1),hasMore:cursor*30<Number((data.page||{}).count)};}
 return {error:'订阅当前不支持此操作'};
}
