function crjText(value){return String(value||"").replace(/<[^>]*>/g," ").replace(/&amp;/g,"&").replace(/&nbsp;/g," ").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim();}
function crjMatch(body,pattern){var match=pattern.exec(body);return match?match[1]:"";}
function crjPath(value){value=String(value||"").replace(/&amp;/g,"&");value=value.replace(/^https:\/\/91crdj\.com/,"");if(!/^\/(duanju|manju|zhenrenju|shipin)\/\d+-[^/?#]+\/(?:\d+\/)?$/.test(value))throw new Error("91CRDJ 内容地址无效");return value;}
function crjDrama(path,title,cover){var id=crjPath(path).replace(/^\/|\/$/g,"");return {id:"crj91:"+id,source:"crj91",sourceId:id,title:crjText(title),cover:cover?resolveURL("https://91crdj.com/",String(cover).replace(/&amp;/g,"&")).replace(/^http:/,"https:"):"",category:"成人短剧",description:"",episodes:0};}
function* crjGet(route){return yield* http("https://91crdj.com"+route,{headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36","Referer":"https://91crdj.com/"}});}
function crjCards(body){var pattern=/<a\b[^>]*class="[^"]*\bcard\b[^"]*"[^>]*>[\s\S]*?<\/a>/gi,rows=[],seen={},match;while((match=pattern.exec(body))&&rows.length<500){try{var path=crjPath(crjMatch(match[0],/href="([^"]+)"/i));if(seen[path])continue;seen[path]=true;var title=crjMatch(match[0],/data-track-item-name="([^"]*)"/i)||crjMatch(match[0],/<h3[^>]*>([\s\S]*?)<\/h3>/i),cover=crjMatch(match[0],/<img\b[^>]*data-src="([^"]+)"/i)||crjMatch(match[0],/<img\b[^>]*\ssrc="([^"]+)"/i);if(title)rows.push(crjDrama(path,title,cover));}catch(_){}}return rows;}
function* sourceExecute(action,input,state){var categories=[["duanju","风月短剧"],["manju","风月漫剧"],["zhenrenju","真人剧"],["shipin","风月视频"]];
 if(action==="categories")return {items:categories.map(function(pair){return {id:pair[0],name:pair[1]};})};
 if(action==="catalog"||action==="search"||action==="check"){var page=Number(input.page)||1,category=input.category||"duanju";if(!categories.some(function(pair){return pair[0]===category;}))throw new Error("91CRDJ 分类无效");if(input.query&&page>1)return empty();var body=yield* crjGet(input.query?"/search/?"+query({keyword:input.query}):"/"+category+"/"+(page>1?"page/"+page+"/":"")),items=crjCards(body),pattern=/\/page\/(\d+)\//g,match,pages=page;while((match=pattern.exec(body)))pages=Math.max(pages,Number(match[1]));return {items:items,page:page,totalPages:pages>page?pages:0,hasMore:!input.query&&page<pages,count:items.length};}
 var drama=input.drama||{},path=crjPath("/"+String(drama.sourceId||"")+"/");
 if(action==="detail"||action==="metadata"){var body=yield* crjGet(path),title=crjMatch(body,/<h1[^>]*class="[^"]*detail-title[^"]*"[^>]*>([\s\S]*?)<\/h1>/i);if(!title)throw new Error("91CRDJ 详情缺少标题");var cover=crjMatch(body,/<div[^>]*class="[^"]*d-poster[^"]*"[^>]*>[\s\S]*?<img[^>]*src="([^"]+)"/i),value=Object.assign({},drama,crjDrama(path,title,cover)),grid=crjMatch(body,/<div[^>]+class="[^"]*ep-grid[^"]*"[^>]*>([\s\S]*?)<\/div>/i)||body,pattern=/<a[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi,chapters=[],seen={},match;while((match=pattern.exec(grid))){var episode;try{episode=crjPath(match[1]);}catch(_){continue;}if(episode.indexOf(path)!==0||!/^\d+\/$/.test(episode.slice(path.length))||seen[episode])continue;seen[episode]=true;var name=crjText(match[2]),order=Number((name.match(/\d+/)||[])[0])||chapters.length+1;chapters.push({id:"crj91:"+drama.sourceId+":"+episode,source:"crj91",pageURL:"https://91crdj.com"+episode,currentEpisode:order,title:name||"第 "+order+" 集"});}if(!chapters.length)throw new Error("91CRDJ 暂无分集");value.description=crjText(crjMatch(body,/<p[^>]*id="viBody"[^>]*>([\s\S]*?)<\/p>/i));value.episodes=chapters.length;return {drama:value,chapters:chapters.sort(function(a,b){return a.currentEpisode-b.currentEpisode;})};}
 if(action==="resolve"){var page=String((input.chapter||{}).pageURL||""),ep=crjPath(page);if(ep.indexOf(path)!==0)throw new Error("91CRDJ 分集不匹配");var parts=ep.match(/\/(\d+)-[^/]+\/(\d+)\/$/),media="";if(parts){try{var data=JSON.parse(yield* crjGet("/videos/"+parts[1]+"/episodes/"+parts[2]+"/playback"));media=url((data.data||{}).src);}catch(_){}}if(!media){var body=yield* crjGet(ep),encoded=crjMatch(body,/"src"\s*:\s*"((?:\\.|[^"\\])*)"/);if(encoded)media=JSON.parse('"'+encoded+'"');}if(!url(media))throw new Error("91CRDJ 没有可播放链路");return {url:media,quality:0,qualities:[],headers:{Referer:"https://91crdj.com/"}};}
 throw new Error("91CRDJ 不支持此操作");
}
