var dsdBase="https://www.dsd.com.se",dsdUA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
function* dsdGet(route){return yield* http(dsdBase+route,{headers:{"User-Agent":dsdUA,Referer:dsdBase+"/"}});}
function dsdCover(body){var value=attr(body,"img[data-original]","data-original")||attr(body,"img[data-src]","data-src")||attr(body,"img[src]","src"),style=attr(body,"[style]","style"),match=/url\(\s*["']?([^"')]+)/i.exec(style);return resolveURL(dsdBase+"/",value||(match?match[1]:""));}
function dsdPlayer(body){return assignment(body,/\bplayer_[a-zA-Z0-9_]+\s*=\s*/)||{};}
function dsdDrama(id,title,cover){return {id:"dsd:"+id,source:"dsd",sourceId:id,title:title,cover:cover||"",description:"",category:"视频",episodes:1};}
function dsdIdentity(body,player,id,line,episode){if(Object.keys(player).length){if(String(player.id)!==id||Number(player.sid)!==line||Number(player.nid)!==episode)throw new Error("帝果播放分集不符");}else if(line!==1||episode!==1||!nodes(body,'.video-info .btn-favs[data-id="'+id+'"]').length)throw new Error("帝果未返回所请求视频");}
function dsdSplit(value){var result=[],depth=0,start=0;for(var i=0;i<value.length;i++){if(value[i]==='(')depth++;if(value[i]===')')depth--;if(value[i]==='+'&&depth===0){if(value.slice(start,i).trim())result.push(value.slice(start,i));start=i+1;}}if(value.slice(start).trim())result.push(value.slice(start));return result;}
function dsdDigit(value){value=value.trim();if(value.indexOf("(oﾟｰﾟo)")>=0)return 'u';if(value.indexOf("(ﾟДﾟ).ﾟΘﾟﾉ")>=0)return 'b';[["(c^_^o)","0"],["(ﾟΘﾟ)","1"],["(o^_^o)","3"],["(ﾟｰﾟ)","4"]].forEach(function(pair){value=value.split(pair[0]).join(pair[1]);});if(value.length>4096||!/^[\d()+\-*/%\s]+$/.test(value))throw new Error("帝果签名表达式变化");var n=Function('return ('+value+')')();if(!Number.isInteger(n))throw new Error("帝果签名表达式无效");return String(n);}
function dsdSigned(body){var marker="(ﾟДﾟ) ['_'] ( (ﾟДﾟ) ['_']",start=body.indexOf(marker);if(start<0)return '';var end=body.lastIndexOf("+ (ﾟДﾟ)[ﾟoﾟ]");if(end<start)return '';var result='';body.slice(start,end).split("(ﾟДﾟ)[ﾟεﾟ]+").slice(1).forEach(function(token){var digits=dsdSplit(token).map(dsdDigit).join('');if(/^u[a-f\d]{4}$/i.test(digits))result+=String.fromCharCode(parseInt(digits.slice(1),16));else if(/^[0-7]+$/.test(digits))result+=String.fromCharCode(parseInt(digits,8));if(result.length>65536)throw new Error("帝果签名数据过大");});var match=/\bvar\s+vPath\s*=\s*["']([^"']+)["']/.exec(result);return match?match[1]:'';}
function* sourceExecute(action,input,state){
 if(action==="categories"){if(state.categories)return {items:state.categories};var body=yield* dsdGet('/'),seen={},items=[];nodes(body,'a[href]').forEach(function(row){var match=/\/vod\/type\/id\/(\d+)/.exec(row.attributes.href||''),name=String(row.text).replace(/\s+/g,' ').trim();if(match&&!seen[match[1]]&&name&&name.length<=48){seen[match[1]]=true;items.push({id:match[1],name:name});}});if(!items.length||items.length>32)throw new Error("帝果分类没有返回");state.categories=items;return {items:items};}
 if(action==="catalog"||action==="search"||action==="check"){var category=input.category;if(!category){var data=yield* sourceExecute('categories',{},state);category=data.items[0].id;}if(!/^\d+$/.test(category))throw new Error("帝果分类无效");var page=Number(input.page)||1,route=input.query?'/index.php/vod/search.html?'+query({wd:input.query,page:page}):'/index.php/vod/type/id/'+category+'/page/'+page+'.html',body=yield* dsdGet(route),seen={},items=[];nodes(body,'a.video-item,a.video-surface').forEach(function(row){var match=/\/vod\/(?:play|detail)\/id\/(\d+)/.exec(row.attributes.href||'');if(!match||seen[match[1]])return;seen[match[1]]=true;var title=nodeText(row.html,'.video-desc,.surface-title,.video-title,.title')||row.attributes.title||attr(row.html,'img','alt');if(!title)throw new Error("帝果目录标题无效");var drama=dsdDrama(match[1],title,dsdCover(row.html));drama.views=nodeText(row.html,'.video-item-tag-hits,.counts').replace(/次$/,'');drama.vip=nodes(row.html,'.video-item-tag-is-vip,.vip-tag').length>0;items.push(drama);});var pages=page;nodes(body,'.el-pagination a,.pagination a,.mac_pages a').forEach(function(row){var match=/\/page\/(\d+)/.exec(row.attributes.href||'');if(match)pages=Math.max(pages,Number(match[1]));});return {items:items,page:page,totalPages:pages,hasMore:page<pages,count:items.length};}
 var drama=input.drama||{},id=String(drama.sourceId||'');if(!/^\d+$/.test(id))throw new Error("帝果视频标识无效");
 if(action==="detail"||action==="metadata"){var body=yield* dsdGet('/index.php/vod/play/id/'+id+'/sid/1/nid/1.html'),player=dsdPlayer(body);dsdIdentity(body,player,id,Number(player.sid)||1,Number(player.nid)||1);var data=player.vod_data||{},title=data.vod_name||nodeText(body,'.video-info h1,.video-info h2,.video-info h3');if(!title)throw new Error("帝果详情没有标题");var value=Object.assign({},drama,dsdDrama(id,title,resolveURL(dsdBase+'/',player.poster||dsdCover(body)))),line=Number(player.sid)||1,current=Number(player.nid)||1,chapters=[],seen={};function add(ep,title){if(seen[ep]||!Number.isInteger(ep)||ep<1)return;seen[ep]=true;chapters.push({id:'dsd:'+id+':'+line+'-'+ep,source:'dsd',line:line,currentEpisode:ep,title:title||'第 '+ep+' 集'});}add(current,'');nodes(body,'a[href]').forEach(function(row){var match=/\/vod\/play\/id\/(\d+)\/sid\/(\d+)\/nid\/(\d+)\.html/.exec(row.attributes.href||'');if(match&&match[1]===id&&Number(match[2])===line)add(Number(match[3]),String(row.text).trim());});value.episodes=chapters.length;value.description=nodeText(body,'.video-info .desc');value.tags=String(data.vod_class||'').split(',').filter(Boolean);value.vip=nodes(body,'.noVip,.openVip').length>0;return {drama:value,chapters:chapters.sort(function(a,b){return a.currentEpisode-b.currentEpisode;})};}
 if(action==='resolve'){var ep=input.chapter||{},parts=String(ep.id||'').split(':').pop().split('-'),line=Number(ep.line||parts[0]),episode=Number(ep.currentEpisode||parts[1]);if(!Number.isInteger(line)||!Number.isInteger(episode)||line<1||episode<1)throw new Error("帝果分集无效");var route='/index.php/vod/play/id/'+id+'/sid/'+line+'/nid/'+episode+'.html',body=yield* dsdGet(route),player=dsdPlayer(body);dsdIdentity(body,player,id,line,episode);if(Number(player.trysee)>0)throw new Error("帝果仅提供试看，不能播放正片");var address=String(player.url||'');if(String(player.encrypt)==='1')address=decodeURIComponent(address);else if(String(player.encrypt)==='2')address=decodeURIComponent(base64decode(address));else if(player.encrypt!==undefined&&String(player.encrypt)!=='0')throw new Error("帝果播放编码变化");if(!address&&line===1&&episode===1){var poster=resolveURL(dsdBase+route,player.poster||dsdCover(body)),fallback=poster.match(/^(https:\/\/[^/]+)(\/video[0-9]*\/[^?#]*\/)1\.(?:jpg|jpeg|png|webp)(?:[?#].*)?$/i);if(fallback&&fallback[1]===dsdBase)address=fallback[1]+fallback[2]+'1000k/index.m3u8';}address=resolveURL(dsdBase+route,address);if(!/^https:\/\//.test(address)||! /\.(m3u8|mp4)(\?|$)/i.test(address))throw new Error("帝果没有正片播放地址");var referer=dsdBase+route;if(address.indexOf('sign=')<0){var path=address.replace(/^https:\/\/[^/]+/,''),signedBody=yield* dsdGet('/addons/vplayer/?url='+encodeURIComponent(path)+'&jump='),signed=dsdSigned(signedBody);if(signed){address=resolveURL(dsdBase+'/addons/vplayer/',signed);referer=dsdBase+'/addons/vplayer/';}}return {url:address,quality:0,qualities:[],headers:{Referer:referer,'User-Agent':dsdUA}};}
 throw new Error("帝果不支持此操作");
}
