"use strict";
var hanimeBase="https://hanime1.me";
var hanimeGenres=["裏番","泡麵番","Motion Anime","3DCG","2.5D","2D動畫","AI生成","MMD","Cosplay","新番預告"];
var hanimeHeaders={"Referer":hanimeBase+"/"};
function hanimeCloudflareChallenge(body){return /(?:_cf_chl_opt|cf-chl-|cdn-cgi\/challenge-platform|<title>\s*just a moment|attention required!|verify you are human)/i.test(String(body||""));}
function* hanimeGet(address,referer){var response=yield {type:"http",url:address,method:"GET",headers:{"Referer":referer||hanimeHeaders.Referer},credential:true},status=Number(response&&response.status)||0,body=String(response&&response.text||"");if(hanimeCloudflareChallenge(body))throw new Error("Hanime 页面要求 Cloudflare 浏览器验证。请在网页端完成验证后，在来源设置中更新 hanime1.me Cookie。");if(status!==200){if(status===403||status===503)throw new Error("Hanime 页面请求被拒绝（HTTP "+status+"）。若网页显示 Cloudflare 验证，请先在网页端完成后更新 Cookie。");throw new Error("Hanime 页面请求失败（HTTP "+status+"）");}return body;}
function hanimeAddress(base,value){var address=resolveURL(base,String(value||"").trim());return /^https:\/\//i.test(address)?address:"";}
function hanimeVideoCode(value){var match=String(value||"").match(/(?:[?&]v=|\/watch\/)([A-Za-z0-9_-]+)/);return match?match[1]:"";}
function hanimeDrama(card){var href=attr(card.html,"a[href*='watch?v=']","href")||attr(card.html,"a","href"),id=hanimeVideoCode(href),title=nodeText(card.html,"div.title, h4.video-title");if(!id||!title)return null;var cover=hanimeAddress(hanimeBase+"/",attr(card.html,"img","src")||attr(card.html,"img","data-src"));return {id:"hanime:"+id,source:"hanime",sourceId:id,title:title,description:"",cover:cover,episodes:1,category:"成人动漫",tags:[]};}
function hanimeCategories(){return [{id:"",name:"全部"}].concat(hanimeGenres.map(function(name){return {id:name,name:name};}));}
function* hanimeCatalog(input){var page=Math.max(1,Math.floor(Number(input.page)||1)),params={page:page},genre=String(input.category||"");if(input.query)params.query=String(input.query);if(genre&&genre!=="all"){if(hanimeGenres.indexOf(genre)<0)throw new Error("Hanime 分類無效");params.genre=genre;}var body=yield* hanimeGet(hanimeBase+"/search?"+query(params)),items=nodes(body,"div[class^=horizontal-card]").map(hanimeDrama).filter(Boolean);return {items:items,page:page,hasMore:items.length>=24,count:items.length};}
function hanimeDetails(body,id,previous){var title=nodeText(body,"#shareBtn-title");if(!title)throw new Error("Hanime 详情页没有有效标题，页面可能受限或结构已变化");var cover=hanimeAddress(hanimeBase+"/watch?v="+encodeURIComponent(id),attr(body,"video#player","poster")),description=nodeText(body,"div[class^=video-caption-text]"),tags=nodes(body,".single-video-tag a").map(function(row){return String(row.text).replace(/\s+/g," ").trim().replace(/^#/,"");}).filter(Boolean);return Object.assign({},previous||{},{id:"hanime:"+id,source:"hanime",sourceId:id,title:title,description:description,cover:cover,episodes:1,category:"成人动漫",tags:tags});}
function hanimeChapter(id){return {id:"hanime:"+id,episodeId:id,source:"hanime",title:"播放",currentEpisode:1};}
function hanimeChoices(body,pageAddress){var rows=nodes(body,"video#player source"),choices=[];rows.forEach(function(row){var address=hanimeAddress(pageAddress,row.attributes.src),height=parseInt(row.attributes.size||"",10)||0;if(address)choices.push({url:address,height:height,headers:{Referer:pageAddress}});});if(!choices.length){var scripts=nodes(body,"div#player-div-wrapper script");for(var i=0;i<scripts.length;i++){var data=String(scripts[i].text||""),match=/const\s+source\s*=\s*'([^']+)'/.exec(data)||/const\s+source\s*=\s*"([^"]+)"/.exec(data);if(!match)continue;var source=match[1].replace(/\\\//g,"/"),address=hanimeAddress(pageAddress,source);if(address)choices.push({url:address,height:0,headers:{Referer:pageAddress}});break;}}return choices;}
function* sourceExecute(action,input,state){if(action==="categories")return {items:hanimeCategories()};if(action==="catalog"||action==="search"||action==="check")return yield* hanimeCatalog(input||{});var drama=input.drama||{},chapter=input.chapter||{},id=String(drama.sourceId||chapter.episodeId||String(chapter.id||"").replace(/^hanime:/,""));if(!/^[A-Za-z0-9_-]{1,64}$/.test(id))throw new Error("Hanime 视频标识无效");if(action==="detail"||action==="metadata"){var pageAddress=hanimeBase+"/watch?"+query({v:id}),body=yield* hanimeGet(pageAddress),value=hanimeDetails(body,id,drama);return single(value,hanimeChapter(id));}if(action==="resolve"){var address=hanimeBase+"/watch?"+query({v:id}),html=yield* hanimeGet(address);return select(hanimeChoices(html,address),parseInt(input.height||"",10)||0);}throw new Error("Hanime 不支持此操作");}
