var HG_BASE="https://api5-normal-sinfonlineb.fqnovel.com";
var HG_UA="com.phoenix.read/73532 (Linux; U; Android 16; zh_CN; 25053RT47C; Build/BP2A.250605.031.A3; Cronet/TTNetVersion:04657795 2026-01-23 QuicVersion:c67e9834 2025-09-08)";
var HG_GENRES=[{id:"short_play",name:"真人剧",scene:"default"},{id:"comic_series",name:"漫剧",scene:"comic_series"},{id:"ai_series",name:"AI剧",scene:"ai_series"}];
function hexBytes(text){return text.match(/../g).map(function(item){return parseInt(item,16);});}
function hex(values){return values.map(function(value){return (value&255).toString(16).padStart(2,"0");}).join("");}
function reverseByte(value){var result=0;for(var bit=0;bit<8;bit++){result=(result<<1)|((value>>bit)&1);}return result;}
function hgSign(q,body,now){var timestamp=Math.floor(now/1000),payload=hexBytes(md5(q)).slice(0,4).concat(body?hexBytes(md5(body)).slice(0,4):[0,0,0,0],[0,0,0,0,0,6,11,28],[(timestamp>>>24)&255,(timestamp>>>16)&255,(timestamp>>>8)&255,timestamp&255]);var key=[68,185,185,217,164,174,249,252,164,147,170,117,124,163,194,196,164,150,147,143];for(var i=0;i<20;i++)payload[i]^=key[i];for(var j=0;j<20;j++)payload[j]=(reverseByte(((payload[j]<<4)|(payload[j]>>>4))&255 ^ payload[(j+1)%20])^255^20)&255;return {"X-Gorgon":"8404401c0000"+hex(payload),"X-Khronos":String(timestamp),"X-SS-Req-Ticket":String(now),"X-SS-STUB":body?md5(body).toUpperCase():""};}
function* hgRequest(route,payload,extra,state){var now=Date.now(),params={aid:"8662",app_name:"novelread",version_code:"73532",version_name:"7.3.5.32",manifest_version_code:"73532",update_version_code:"73532",channel:"update_64",device_platform:"android",os:"android",ssmix:"a",device_type:"25053RT47C",device_brand:"Redmi",language:"zh",os_api:"36",os_version:"16",resolution:"1280*2772",dpi:"520",ac:"wifi",device_id:state.deviceId||(state.deviceId="1"+String(now)+String(Math.floor(Math.random()*100000))),iid:state.installId||(state.installId="1"+String(now)+"12345"),_rticket:String(now)};Object.assign(params,extra||{});var q=query(params),body=payload?JSON.stringify(payload):null,headers=Object.assign({"User-Agent":HG_UA,"Accept":"application/json","X-XS-From-Web":"0","Sdk-Version":"2","Content-Type":"application/json; charset=utf-8"},hgSign(q,body,now));var result=yield* json(HG_BASE+route+"?"+q,{method:payload?"POST":"GET",body:body,headers:headers});if(result.code&&String(result.code)!=="0")throw new Error("Hongguo unavailable");return result.data||{};}
function hgDrama(raw,category){var outer=raw;raw=raw.video_data||raw;var id=String(first(raw,["series_id_str","series_id"],first(outer,["series_id_str","series_id","keyword"],"")));var schema=raw.category_schema;try{if(typeof schema==='string')schema=JSON.parse(schema);}catch(error){schema=[];}var tags=array(raw.tags).concat(array(raw.category_list),array(schema)).map(function(item){return typeof item==="string"?item:first(item,["name","category_name"],"");}).filter(Boolean);if(category&&tags.indexOf(category)<0)tags.push(category);return {id:"hongguo:"+id,source:"hongguo",sourceId:id,title:String(first(raw,["series_title","series_name","title"],id)),description:String(first(raw,["series_intro","video_desc"],"")),cover:String(first(raw,["series_cover","cover"],"")),episodes:Number(raw.episode_cnt)||0,category:String(first(raw,['category_name','categoryName','category'],tags[0]||category||'短剧')),tags:tags,heat:String(first(raw,["heat","hot_value","series_heat"],"")),views:String(first(raw,['series_play_cnt','play_cnt'],'')),onlineDate:String(first(raw,["publish_time","online_time"],"")),releaseStatus:String(raw.series_status)==='1'?'finished':String(raw.series_status)==='0'?'ongoing':''};}
function hgContentKey(value){var bytes=base64bytes(value);var tag=(bytes[0]^bytes[1]^bytes[2])-48,n=bytes.length-tag-1;if(tag<1||n<33)throw new Error("Invalid key");var seed=bytes[bytes.length-tag-2]^bytes[bytes.length-tag-1],label=bytes.slice(-tag).map(function(x){return String.fromCharCode(x^seed);}).join("");if(label==="app_v2"||label==="web_v2")throw new Error("Unsupported key");var even=250,odd=85,decoded=[];for(var i=0;i<n;i++){var current=bytes[i+1],previous=i%2?odd:even;if(i%2)odd=current;else even=current;var count=i.toString(2).replace(/0/g,"").length;decoded.push((previous^current)-21-count&255);}if(n-parseInt(String.fromCharCode(decoded[0]),36)-1!==32)throw new Error('Invalid padding');var key=decoded.slice(1,33).map(function(x){return String.fromCharCode(x);}).join("");if(!/^[0-9a-fA-F]{32}$/.test(key))throw new Error("Invalid key");return key;}
function hgChoices(model){var list=model&&model.video_list,rows=Array.isArray(list)?list:Object.keys(list||{}).map(function(key){return list[key];}),choices=[];rows.forEach(function(row){var meta=row.video_meta||{},codec=String(meta.codec_type||'').toLowerCase();if(codec==='bytevc2'||String(row.gear_des_key||'').toLowerCase().indexOf('bytevc2')>=0)return;var encryption=row.encrypt_info||{},key='';try{if(encryption.spade_a||encryption.encrypt===true||encryption.encryption_method==='cenc-aes-ctr')key=hgContentKey(encryption.spade_a);}catch(error){return;}var definition=String(meta.definition||'').match(/\d+/),height=definition?Number(definition[0]):Number(meta.vheight)||0;if(!definition&&Number(meta.vwidth)>0&&(height===0||Number(meta.vwidth)<height))height=Number(meta.vwidth);var addresses=[];['main_url','backup_url','backup_url_1','backup_url_2','backup_urls','url_list'].forEach(function(field){var values=Array.isArray(row[field])?row[field]:[row[field]];values.forEach(function(value){if(!value)return;var address=String(value);try{if(!/^https?:/.test(address))address=base64decode(address);}catch(error){return;}if(/^https:\/\//.test(address)&&addresses.indexOf(address)<0)addresses.push(address);});});addresses.forEach(function(address){choices.push({url:address,height:height,key:key,headers:{'Referer':'https://novel.snssdk.com/'}});});});return choices;}
function* hgApp(action,input,state){var drama=input.drama||{},id=drama.sourceId||String(drama.id||"").split(":").pop();
 if(action==="categories")return {items:HG_GENRES.map(function(item){return {id:item.id,name:item.name};})};
 if(action==="catalog"||action==="check"){
  state.feeds=state.feeds||{};var genres=input.category?HG_GENRES.filter(function(item){return item.id===input.category;}):HG_GENRES;if(!genres.length)throw new Error('分类无效');var items=[],more=false;
  for(var g=0;g<genres.length;g++){var genre=genres[g],feed=state.feeds[genre.id]||{offset:0,session:''};if(input.page===1||action==='check')feed={offset:0,session:''};var payload={req_scene:genre.scene,offset:feed.offset||0,limit:18,req_type:"only_content",need_selector_panel:false,client_req_type:feed.offset?2:3,session_id:feed.session||"",filter_ids:"",select_items:{genre:[genre.id],sort:["online_time"],gender:[],category_dim_theme:[],category_dim_role:[],category_dim_epoch:[],online_time:[],creation_status:[]}};
  var data=yield* hgRequest("/reading/distribution/category/landpage/v/",payload,null,state);if(!Array.isArray(data.video_data))throw new Error('分类数据格式异常');var rows=data.video_data.map(function(row){return hgDrama(row,genre.name);}).filter(function(row){return /^\d+$/.test(row.sourceId)&&row.title;});if(data.has_more&&Number(data.next_offset)<=Number(feed.offset||0))throw new Error("Cursor did not advance");feed.offset=Number(data.next_offset||0);feed.session=data.session_id||"";state.feeds[genre.id]=feed;items=items.concat(rows);more=more||!!data.has_more;}return {items:items,count:items.length,hasMore:more};
 }
 if(action==="detail"||action==="metadata"){
  var data=yield* hgRequest("/novel/player/video_detail/v1/",{series_id:id},null,state),row=data.video_data||{};if(String(row.series_id_str||row.series_id)!==id)throw new Error("Wrong series");var parsed=hgDrama(row,drama.category);var chapters=array(row.video_list).map(function(video){return {id:"hongguo:"+id+":"+video.vid,title:"第"+video.vid_index+"集",currentEpisode:Number(video.vid_index),videoId:String(video.vid)};}).sort(function(a,b){return a.currentEpisode-b.currentEpisode;});if(!chapters.length||chapters.length<Number(row.episode_cnt||0))throw new Error("Incomplete episodes");return {drama:parsed,chapters:chapters};
 }
 if(action==="resolve"){
  var episode=input.chapter||{},videoId=episode.videoId||String(episode.id||"").split(":").pop();if(!/^\d+$/.test(videoId))throw new Error("Invalid episode");var data=yield* hgRequest("/novel/player/video_model/v1/",{video_id:videoId,content_type:1,biz_param:{need_all_video_definition:true,video_platform:3}},null,state),model=typeof data.video_model==="string"?JSON.parse(data.video_model):data.video_model;return select(hgChoices(model),Number(input.quality||0));
 }
 return {error:"此站源版本尚不支持该操作"};
}
