function hjData(value){return value.data!==undefined&&value.id===undefined&&value.items===undefined&&value.url===undefined?value.data:value;}
function* hjRequest(route,params,state){
 if(!state.token||Date.now()-Number(state.tokenAt||0)>3600000){var guest=yield* json("https://api.huangju.net/auth/guest",{method:"POST",headers:{"Content-Type":"application/json","Origin":"https://huangju.net","Referer":"https://huangju.net/"},body:JSON.stringify({deviceId:state.deviceId||(state.deviceId="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var n=Math.floor(Math.random()*16);return (c==='x'?n:(n&3)|8).toString(16);} )))});state.token=guest.token||(guest.data||{}).token;if(!state.token)throw new Error("剧果访客授权失败");state.tokenAt=Date.now();}
 var response=yield {type:"http",url:"https://api.huangju.net"+route+(params?"?"+query(params):""),method:"GET",headers:{Authorization:"Bearer "+state.token,"Origin":"https://huangju.net","Referer":"https://huangju.net/","Accept":"application/json","User-Agent":"Mozilla/5.0"}};
 if(response.status===401){state.token="";throw new Error("剧果访客授权过期，请重试");}if(response.status!==200)throw new Error("剧果请求失败");return {data:hjData(JSON.parse(response.text)),cookies:response.mediaCookies||[]};
}
function hjDrama(row,sourceId){var id=String(row.id||""),slug=String(row.slug||""),sid=sourceId||slug+"-"+id;if(!id||!row.title||!sid.endsWith("-"+id))throw new Error("剧果剧集信息无效");var names=array(row.categories).map(function(item){return typeof item==='string'?item:item.name;}).filter(Boolean);if(row.category)names.unshift(typeof row.category==='string'?row.category:row.category.name);return {id:"huangju:"+sid,source:"huangju",sourceId:sid,title:row.title,cover:url(row.coverUrl),description:row.description||"",episodes:Number(row.totalEpisodes)||0,category:names[0]||"短剧",tags:names,releaseStatus:row.status==="completed"?"finished":row.status||""};}
function* sourceExecute(action,input,state){
 if(action==="categories"){var value=(yield* hjRequest("/categories",null,state)).data;if(!Array.isArray(value)||value.length>300)throw new Error("剧果分类无效");return {items:[{id:"@new",name:"最新"}].concat(value.filter(function(row){return row.slug!=="hot";}).map(function(row){return {id:row.slug,name:row.name};}))};}
 if(action==="catalog"||action==="search"||action==="check"){var page=Number(input.page)||1,params={page:page};if(input.query)params.q=input.query;else if(input.category==="@new")params.sort="new";else if(input.category)params.category=input.category;else params.sort="hot";var value=(yield* hjRequest("/dramas",params,state)).data;if(!Array.isArray(value.items)||value.items.length>500||value.page&&Number(value.page)!==page)throw new Error("剧果目录页无效");var size=Number(value.pageSize)||20,pages=Math.ceil(Number(value.total)/size)||0;return {items:value.items.map(function(row){return hjDrama(row);}),page:page,totalPages:pages,hasMore:pages?page<pages:value.items.length>=size,count:value.items.length};}
 var drama=input.drama||{},sid=String(drama.sourceId||"");if(!sid||/[\/:?#%|\\]/.test(sid))throw new Error("剧果剧集标识无效");
 if(action==="detail"||action==="metadata"){var value=(yield* hjRequest("/dramas/"+encodeURIComponent(sid),null,state)).data;if(!Array.isArray(value.episodes)||value.episodes.length>10000)throw new Error("剧果分集目录无效");var seen={},chapters=value.episodes.filter(function(ep){return ep.playable!==false;}).map(function(ep,index){var id=String(ep.id||""),order=Number(ep.epNo)||index+1;if(!id||seen[id])throw new Error("剧果分集重复或无效");seen[id]=true;return {id:"huangju:"+sid+":"+id,episodeId:id,source:"huangju",title:"第 "+order+" 集",currentEpisode:order};}).sort(function(a,b){return a.currentEpisode-b.currentEpisode;});return {drama:hjDrama(value,sid),chapters:chapters};}
 if(action==="resolve"){var ep=input.chapter||{},id=String(ep.episodeId||String(ep.id||"").split(":").pop());if(!id||/[\/:?#%|\\]/.test(id))throw new Error("剧果分集标识无效");var value=yield* hjRequest("/play/"+encodeURIComponent(id),null,state);if(!url(value.data.url))throw new Error("剧果未返回播放地址");if(value.cookies.length!==3)throw new Error("剧果媒体凭据不完整");return {url:value.data.url,quality:0,qualities:[],headers:{Referer:"https://huangju.net/","User-Agent":"Mozilla/5.0"},mediaCookies:value.cookies,expiresAt:typeof value.data.expiresAt==="string"?Date.parse(value.data.expiresAt)||0:Number(value.data.expiresAt)||0};}
 throw new Error("剧果不支持此操作");
}
