"use strict";
function* execute(action,input,state){state=state||{};if(action==="metadata")action="detail";var result=yield* sourceExecute(action,input,state);result=result||{};if(result.error)throw new Error(result.error);if(result.drama)result.drama=normalizeDrama(result.drama);if(Array.isArray(result.items))result.items=result.items.map(function(row){if(row.drama){row.drama=normalizeDrama(row.drama);return row;}return row.sourceId?normalizeDrama(row):row;});result.state=state;return result;}
function normalizeDrama(row){return Object.assign({},row,{description:String(first(row,["description","desc","intro"])),episodes:Number(first(row,["episodes","totalEpisode","episodeCount"],0))||0,category:String(first(row,["category","categoryName"])),sourceId:String(row.sourceId||""),title:String(first(row,["title","name"],"未命名")),tags:array(row.tags).filter(function(value){return typeof value==="string";})});}
function query(params) { return Object.keys(params).sort().map(function(key){return encodeURIComponent(key)+"="+encodeURIComponent(String(params[key])).replace(/%20/g,"+");}).join("&"); }
function first(object,keys,fallback){for(var i=0;i<keys.length;i++){var value=object&&object[keys[i]];if(value!==undefined&&value!==null&&value!=="")return value;}return fallback===undefined?"":fallback;}
function array(value){return Array.isArray(value)?value:[];}
function url(value){var values=array(value&&value.url_list);for(var i=0;i<values.length;i++){if(/^https:\/\//.test(values[i]))return values[i];}return typeof value==="string"&&/^https:\/\//.test(value)?value:"";}
function* http(address,options){options=options||{};var response=yield {type:"http",url:address,method:options.method||"GET",headers:options.headers||{},body:options.body,credential:!!options.credential,sign:!!options.sign};if(!response||response.status!==200){var error=new Error("HTTP failed");error.sourceError="http";error.httpStatus=response&&response.status||0;throw error;}return response.text;}
function* json(address,options){var data=JSON.parse(yield* http(address,options));if(data.status_code&&data.status_code!==0)throw new Error("API status");return data;}
function empty(){return {items:[],hasMore:false};}
function assignment(body,pattern){var match=pattern.exec(body);if(!match)return null;var start=match.index+match[0].length;while(/\s/.test(body[start]||"")&&start<body.length)start++;var depth=0,quoted=false,escaped=false;for(var i=start;i<body.length;i++){var c=body[i];if(escaped){escaped=false;continue;}if(quoted&&c==='\\'){escaped=true;continue;}if(c==='"'){quoted=!quoted;continue;}if(quoted)continue;if(c==='{'||c==='[')depth++;else if(c==='}'||c===']'){if(--depth===0)return JSON.parse(body.slice(start,i+1));}}throw new Error("页面参数不完整");}
function nodes(body,selector){return Array.from(htmlSelect(body,selector));}
function nodeText(body,selector){var row=nodes(body,selector)[0];return row?String(row.text).replace(/\s+/g," ").trim():"";}
function attr(body,selector,key){var row=nodes(body,selector)[0];return row?row.attributes[key]||"":"";}
function single(drama,chapter){return {drama:drama,chapters:[chapter||{id:drama.sourceId,title:"播放",currentEpisode:1}]};}
function select(choices,height){choices=choices.filter(function(value){return value.url&&/^https:\/\//.test(value.url);}).sort(function(a,b){return b.height-a.height;});if(!choices.length)throw new Error("No playable media");var selected=height?choices.find(function(value){return value.height<=height;})||choices[choices.length-1]:choices[0];return {url:selected.url,quality:selected.height||0,qualities:choices.map(function(value){return value.height||0;}),headers:selected.headers||{},decryptionKey:selected.key||"",variants:[selected].concat(choices.filter(function(value){return value.url!==selected.url;})).slice(0,16).map(function(value){return {url:value.url,quality:value.height||0,headers:value.headers||{},decryptionKey:value.key||""};})};}
