var soraniBase="https://api.sorani.cc/sorani-cms/api";
function* soraniRequest(route,params){var value=yield* json(soraniBase+route+(params?"?"+query(params):""),{headers:{"User-Agent":"Mozilla/5.0","Referer":"https://www.sorani.net/","Origin":"https://www.sorani.net"}});if(value.code!==undefined&&value.code!==0&&value.code!==200)throw new Error("青空次元接口返回错误");return value.data===undefined?value:value.data;}
function soraniDrama(row){var id=String(first(row,["id","videoId"])),title=String(first(row,["title","name","videoTitle"]));if(!/^\d+$/.test(id)||!title)throw new Error("青空次元剧集信息无效");var cover=String(first(row,["cover","coverLarge","coverSmall","coverThumb","backgroundImage"]));if(cover.indexOf("//")===0)cover="https:"+cover;else if(cover.indexOf("/")===0)cover="https://www.sorani.net"+cover;return {id:"sorani:"+id,source:"sorani",sourceId:id,title:title,description:String(first(row,["summary","description","intro","desc"])),cover:cover,episodes:Number(first(row,["episodeCount","totalEpisode","total"],0)),category:String(first(row,["categoryName","category"],"番剧")),tags:array(row.tags||row.tagList).map(String)};}
function* sourceExecute(action,input,state){
 if(action==="categories")return {items:[{id:"1",name:"TV番剧"},{id:"2",name:"剧场动画"},{id:"5",name:"特摄剧场"}]};
 if(action==="catalog"||action==="search"||action==="check") {var page=Number(input.page)||1,params={page:page,size:24};if(input.query)params.keyword=input.query;else if(input.category)params.categoryId=input.category;var result=yield* soraniRequest(input.query?"/video/search":"/video",params),rows=Array.isArray(result)?result:first(result,["records","list","items","rows"],null);if(!Array.isArray(rows)||rows.length>500)throw new Error("青空次元目录格式无效");var total=Number(result.total),pages=Number.isFinite(total)?Math.ceil(total/24):0;return {items:rows.map(soraniDrama),page:page,totalPages:pages,hasMore:pages?page<pages:rows.length>=24,count:rows.length};}
 var drama=input.drama||{},id=String(drama.sourceId||"" );if(!/^\d+$/.test(id))throw new Error("青空次元剧集标识无效");
 if(action==="detail"||action==="metadata") {var row=yield* soraniRequest("/video/"+id),value=soraniDrama(row);if(value.sourceId!==id||!Array.isArray(row.episodes)||row.episodes.length>10000)throw new Error("青空次元分集目录无效");var seen={},orders={},chapters=row.episodes.filter(function(ep){return ep.enabled!==false;}).map(function(ep,index){var eid=String(first(ep,["episodeId","id"])),order=Number(ep.episodeOrder)||index+1;if(!/^\d+$/.test(eid)||seen[eid]||orders[order])throw new Error("青空次元分集重复或无效");seen[eid]=orders[order]=true;return {id:"sorani:"+id+":"+eid,episodeId:eid,source:"sorani",title:String(first(ep,["episodeLabel","title","displayTitle"],"第 "+order+" 集")),currentEpisode:order};}).sort(function(a,b){return a.currentEpisode-b.currentEpisode;});return {drama:value,chapters:chapters};}
 if(action==="resolve") {var ep=input.chapter||{},eid=String(ep.episodeId||String(ep.id||"").split(":").pop());if(!/^\d+$/.test(eid))throw new Error("青空次元分集标识无效");var playback=yield* soraniRequest("/video/episode/"+eid+"/play",{lineCode:"anime_jp_m3u8"}),address=String(first(playback,["playUrl","url"]));if(!/^https:\/\//.test(address))throw new Error("青空次元暂无有效播放地址");return {url:address,quality:0,qualities:[],headers:{Referer:"https://www.sorani.net/"}};}
 throw new Error("青空次元不支持此操作");
}
