var cmsConfig=typeof sourceConfig!=="undefined"?sourceConfig:{};
cmsConfig.categories=array(cmsConfig.categories).map(function(row){return Array.isArray(row)?row:[String(row.id),String(row.name)];});
function cmsText(value){return String(value||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#(\d+);/g,function(_,n){return String.fromCodePoint(Number(n));}).replace(/&#x([a-f\d]+);/gi,function(_,n){return String.fromCodePoint(parseInt(n,16));}).replace(/\s+/g," ").trim();}
function cmsMatch(body,pattern){var match=pattern.exec(body);return match?match[1]:"";}
function cmsAddress(address){address=cmsText(address);if(address.indexOf("//")===0)return "https:"+address;if(address.indexOf("/")===0)return cmsConfig.base+address;return address;}
function* cmsGet(route){return yield* http(cmsConfig.base+route,{headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36","Referer":cmsConfig.base+"/"}});}
function cmsDrama(id,title,cover){return {id:cmsConfig.id+":"+id,source:cmsConfig.id,sourceId:id,title:cmsText(title),cover:cmsAddress(cover),description:"",category:cmsConfig.id==="hanxiaoquan"?"韩剧":"影视",episodes:0};}
function cmsCards(body){var han=cmsConfig.id==="hanxiaoquan",pattern=han?/<a href="\/hanxiaoquan\/(\d+)\.html"[^>]*title="([^"]*)"[^>]*class="module-item-pic"/gi:/<a class="video-link" href="\/nv\/(\d+)\.html"[^>]*title="([^"]*)"([\s\S]*?)<\/a>/gi,items=[],seen={},match;while((match=pattern.exec(body))&&items.length<500){if(seen[match[1]])continue;seen[match[1]]=true;var chunk=han?body.slice(match.index,body.indexOf('class="module-item-pic"',pattern.lastIndex)>0?body.indexOf('class="module-item-pic"',pattern.lastIndex):match.index+6000):match[3],cover=cmsMatch(chunk,han?/<img[^>]*data-src="([^"]+)"/i:/data-(?:original|background)="([^"]+)"/i);if(cmsText(match[2]))items.push(cmsDrama(match[1],match[2],cover));}return items;}
function cmsChapters(body,id){var pattern=/<a\b([^>]*\bhref=["'](\/play\/\d+-\d+-\d+\.html)["'][^>]*)>([\s\S]*?)<\/a>/gi,groups={},match;while((match=pattern.exec(body))){var title=cmsText(cmsMatch(match[1],/title=["']([^"']*)["']/i)||match[3]),parts=/\/play\/(\d+)-(\d+)-(\d+)\.html/.exec(match[2]);if(parts[1]!==id)continue;var line=parts[2],entries=groups[line]||(groups[line]=[]);if(entries.some(function(ep){return ep.pageURL===cmsConfig.base+match[2];}))continue;entries.push({id:cmsConfig.id+":"+id+":"+parts[2]+"-"+parts[3],source:cmsConfig.id,pageURL:cmsConfig.base+match[2],title:title||"第 "+(entries.length+1)+" 集",currentEpisode:Number((title.match(/\d+/)||[])[0])||entries.length+1});}var best=[];Object.keys(groups).sort().forEach(function(key){if(groups[key].length>best.length)best=groups[key];});if(!best.length)throw new Error("网页没有可播放分集");return best.sort(function(a,b){return a.currentEpisode-b.currentEpisode;});}
function* sourceExecute(action,input,state){var han=cmsConfig.id==="hanxiaoquan";
 if(action==="categories")return {items:cmsConfig.categories.map(function(pair){return {id:pair[0],name:pair[1]};})};
 if(action==="catalog"||action==="search"||action==="check"){var page=Number(input.page)||1,category=input.category||cmsConfig.categories[0][0];if(!cmsConfig.categories.some(function(pair){return pair[0]===category;}))throw new Error("网页分类不存在");if(input.query&&!han){var rss=yield* cmsGet("/xml/rss.xml"),pattern=/<item\b[^>]*>([\s\S]*?)<\/item>/gi,items=[],match;while((match=pattern.exec(rss))){var title=cmsText(cmsMatch(match[1],/<title[^>]*>([\s\S]*?)<\/title>/i)),id=cmsMatch(match[1],/\/nv\/(\d+)\.html/i);if(id&&title.toLowerCase().indexOf(String(input.query).toLowerCase())>=0)items.push(cmsDrama(id,title,""));}var start=(page-1)*24;return {items:items.slice(start,start+24),page:page,hasMore:start+24<items.length};}
 if(input.query&&page>1)return empty();var route=input.query?"/search.php?"+query({searchword:input.query}):han?"/hxq/"+category+(page>1?"-"+page:"")+".html":"/list/"+category+(page>1?"_"+page:"")+".html",body=yield* cmsGet(route),items=cmsCards(body),pages=page,pattern=new RegExp((han?"/hxq/":"/list/")+category+(han?"-":"_")+"(\\d+)\\.html","g"),match;while((match=pattern.exec(body)))pages=Math.max(pages,Number(match[1]));return {items:items,page:page,totalPages:pages>page?pages:0,hasMore:!input.query&&(page<pages||items.length>=24),count:items.length};}
 var drama=input.drama||{},id=String(drama.sourceId||"");if(!/^\d+$/.test(id))throw new Error("网页剧集标识无效");
 if(action==="detail"||action==="metadata"){var body=yield* cmsGet((han?"/hanxiaoquan/":"/nv/")+id+".html"),title=cmsMatch(body,han?/<h1 class="page-title"[^>]*>([\s\S]*?)<\/h1>/i:/<h1 class="media-title[^"]*"[^>]*>([\s\S]*?)<\/h1>/i);if(!title)throw new Error("网页详情未返回有效标题");var cover=cmsMatch(body,/property="og:image"\s+content="([^"]+)"/i)||cmsMatch(body,han?/<div class="video-cover">[\s\S]*?<img[^>]*data-src="([^"]+)"/i:/<div class="detail-img"><img[^>]+src="([^"]+)"/i),value=Object.assign({},drama,cmsDrama(id,title,cover)),chapters=cmsChapters(body,id);value.episodes=chapters.length;value.description=cmsText(han?cmsMatch(body,/<span class="video-info-itemtitle">(?:剧情|简介)[：:]?<\/span>\s*<div class="video-info-item[^"]*">([\s\S]*?)<\/div>/i):cmsMatch(body,/简介：([\s\S]*?)<\/li>/i));return {drama:value,chapters:chapters};}
 if(action==="resolve"){var address=String((input.chapter||{}).pageURL||"");if(address.indexOf(cmsConfig.base+"/play/"+id+"-")!==0||!/^https:\/\/[^/]+\/play\/\d+-\d+-\d+\.html$/.test(address))throw new Error("播放页与剧集不符");var body=yield* cmsGet(address.slice(cmsConfig.base.length)),media=cmsMatch(body,/var\s+now\s*=\s*["']([^"']+)["']/i)||cmsMatch(body,/(https?:\/\/[^"'\s<>\\]+\.(?:m3u8|mp4)(?:\?[^"'\s<>\\]*)?)/i);media=cmsAddress(media);if(!/^https:\/\//.test(media))throw new Error("网页未返回 HTTPS 播放地址");return {url:media,quality:0,qualities:[],headers:{Referer:cmsConfig.base+"/"}};}
 throw new Error("网页站源不支持此操作");
}
